### ISSUE TITLE
infra: 프로메테우스, 그라파나 추가

### ISSUE THREAD

**Issue by KarmaPol** [Central-MakeUs/Daldal-Server#56]
- 프로메테우스, 그라파나 추가

**Comment by KarmaPol** [comment]
### Docker 그라파나 run 오류
https://github.com/cfbarbero/tick-grafana-docker/issues/1
실행 명령어 추가

### Docker 그라파나 permission 오류
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

**Comment by KarmaPol** [comment]
## 참고 블로그
### 튜토리얼
https://velog.io/@sgjung/Monitoring-간단한-Prometheus-실습w.-docker
### mysql nodeexporter 프로메테우스
https://velog.io/@sojukang/세상에서-제일-쉬운-Prometheus-Grafana-모니터링-설정-MySQL편
### docker-compose 설정
https://velog.io/@swhan9404/Prometheus를-docker로-구성해보기#grafana

**Comment by KarmaPol** [comment]
## 프로메테우스 Docker Swarm 모니터링 공식문서
https://prometheus.io/docs/guides/dockerswarm/

**Comment by KarmaPol** [comment]
### 프로메테우스 Prometheus can't access to docker.sock
- 깃헙 이슈 https://github.com/prometheus/prometheus/issues/8185
- 해결책 https://groups.google.com/g/prometheus-users/c/EuEW0qRzXvg/m/0aqKh_ZABQAJ?pli=1
```
services:
  prometheus:
    image: prom/prometheus:v2.21.0

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-48h}'
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
```
